# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-07-18 03:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deployment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessline',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='businesslines', to=settings.AUTH_USER_MODEL, verbose_name='小组leader'),
        ),
        migrations.AlterField(
            model_name='businessline',
            name='topline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='businesslines', to='deployment.TopLine', verbose_name='顶级业务线'),
        ),
        migrations.AlterField(
            model_name='project',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL, verbose_name='小组leader'),
        ),
        migrations.AlterField(
            model_name='topline',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='toplines', to=settings.AUTH_USER_MODEL, verbose_name='业务线leader'),
        ),
    ]
