# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-07-18 06:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deployment', '0002_auto_20180718_0318'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='businessline',
            options={'verbose_name_plural': '业务小组'},
        ),
        migrations.AlterModelOptions(
            name='deployment',
            options={'permissions': [('view_deployment', 'view deployment')], 'verbose_name_plural': '发布任务'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name_plural': '项目'},
        ),
        migrations.AlterModelOptions(
            name='topline',
            options={'verbose_name_plural': '顶级业务线'},
        ),
        migrations.AlterField(
            model_name='businessline',
            name='name',
            field=models.CharField(max_length=64, unique=True, verbose_name='次级业务线'),
        ),
        migrations.AlterField(
            model_name='topline',
            name='name',
            field=models.CharField(max_length=64, unique=True, verbose_name='顶级业务线'),
        ),
    ]
