# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-07-19 08:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deployment', '0003_auto_20180718_0601'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'permissions': [('deploy_project', 'deploy project')], 'verbose_name_plural': '项目'},
        ),
    ]
