# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-07-13 04:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20180713_0439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='books', to='app.Author', verbose_name='作者'),
            preserve_default=False,
        ),
    ]
